### ISSUE TITLE
backend ssm errors swallowed

### ISSUE THREAD

**Issue by vincentgna** [abtreece/confd#110]
Error is swallowed here:

https://github.com/abtreece/confd/blob/8a76b9a4a11a7ee55682724b0fce537d350e2ead/pkg/backends/ssm/client.go#L93

ideally the line should be:

```go
err = c.client.GetParametersByPathPages(params, 
```

**Comment by abtreece** [comment]
Hey @vincentgna... good catch! Would you be open to PR'ing this fix?

**Comment by abtreece** [comment]
https://github.com/abtreece/confd/releases/tag/v0.19.1

**Comment by vincenthsh** [comment]
just got around to deploying this and realised that when confd was swallowing the errors, it would render empty files but now the file is not generated at all - not sure if a note is required because bumping from 0.19.0 to 0.19.1 is not 100% backward compatible :)
