### ISSUE TITLE
confd using ssm, is using ec2metadata information, instead of giving an option to a region

### ISSUE THREAD

**Issue by SallyBlichWalkMe** [abtreece/confd#131]
Hello,
Thank you for your support on the confd project and for your fork, it's very useful! 

I have an issue regarding the ssm backend part.
I have a gitlab runner, that's is running on ec2 instance, over k8s. And, this runner is trying to deploy to another cluster, which is located on a different region, same goes to the ssm.
When I'm using confd in the current version, it's taking the ec2metadata info, which isn't good for the deployment that I explained before, because it needs to take the region of the cluster that I'm deploying too.

Which is why I forked this repo, and basically changed back to what was in the original repo - https://github.com/kelseyhightower/confd

This is what exists now:
https://github.com/abtreece/confd/blob/da2179c0d72d718cc5f3aebdfbf72fb3e2e601d5/pkg/backends/ssm/client.go#L19-L59

This is what I changed, based on the original repo:
https://github.com/SallyBlichWalkMe/confd/blob/1beb7e4cc3a078bae14b8e72300d268b95d0cf73/pkg/backends/ssm/client.go#L17-L41

The region is configured by env var, before running confd:
`AWS_REGION=$AWS_REGION`

**Comment by abtreece** [comment]
Thanks for reporting this @SallyBlichWalkMe! I'll try to dig in to the issue in the next week or two.

**Comment by abtreece** [comment]
Fixed by https://github.com/abtreece/confd/releases/tag/v0.19.2
