### ISSUE TITLE
Vault: Nested values in vault_v2 is not being read.

### ISSUE THREAD

**Issue by jbsmith7741** [abtreece/confd#244]
Nested Values in vault_v2 are not being evaluated recursively. Comparing output of the integration tests for vault-v1 and vault-v2 for the nested-test, we see that the server sections are not being populated in vault-v2. 

vault-v1
```
upstream app {
    server {"app1":"10.0.1.10:8080"};
    server {"app2":"10.0.1.11:8080"};
}

server {
    server_name  www.example.com;
    location / {
        proxy_pass        http://app;
        proxy_redirect    off;
        proxy_set_header  Host             $host;
        proxy_set_header  X-Real-IP        $remote_addr;
        proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
   }
}
```

vault-v2
```
upstream app {
}

server {
    server_name  www.example.com;
    location / {
        proxy_pass        http://app;
        proxy_redirect    off;
        proxy_set_header  Host             $host;
        proxy_set_header  X-Real-IP        $remote_addr;
        proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
   }
}
```

**Comment by abtreece** [comment]
@jbsmith7741 can you provide more details on the environment, versions, etc where this issue is happening?

The automated integration tests running via Github Actions don't seem to be catching the same issue and I'm not currently able to replicate it locally.

**Comment by abtreece** [comment]
> @jbsmith7741 can you provide more details on the environment, versions, etc where this issue is happening?
> 
> The automated integration tests running via Github Actions don't seem to be catching the same issue and I'm not currently able to replicate it locally.

Disregard, I see it now... 🤔

**Comment by abtreece** [comment]
@jbsmith7741 I believe this issue has been fixed. Do note the breaking changes introduced with the refactor...
